import React, { useState, useEffect, useCallback, useRef } from 'react';
import { 
  FileText, 
  Download, 
  Loader2, 
  Clock, 
  TrendingUp, 
  Zap,
  Check,
  RefreshCw,
  Eye
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { UserProfile, Transaction } from '../types';
import { useSettings } from '../context/SettingsContext';
import { MonthlyReport } from './MonthlyReport';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { getFinancialInsights } from '../services/aiService';

interface Props {
  profile: UserProfile;
  transactions: Transaction[];
}

export default function ReportsView({ profile, transactions }: Props) {
  const { formatCurrency } = useSettings();
  const [isGenerating, setIsGenerating] = useState<string | null>(null);
  const [insights, setInsights] = useState<string[]>([]);
  const [reportHistory, setReportHistory] = useState<{id: string, date: string, month: string}[]>([]);
  const [autoGenerate, setAutoGenerate] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Load history
    const history = JSON.parse(localStorage.getItem('nudge_report_history') || '[]');
    setReportHistory(history.reverse());
    
    // Load auto-gen preference
    const autoGen = localStorage.getItem('nudge_auto_generate_report') === 'true';
    setAutoGenerate(autoGen);
    
    // Fetch insights
    getFinancialInsights(transactions, profile).then(setInsights);
  }, [transactions, profile]);

  const addToast = (message: string) => {
    // We don't have a global toast system here, using console for now 
    // or we could implement a local one if needed.
    console.log(message);
  };

  const handleToggleAutoGenerate = () => {
    const newVal = !autoGenerate;
    setAutoGenerate(newVal);
    localStorage.setItem('nudge_auto_generate_report', String(newVal));
  };

  const downloadReport = async (month: string, id: string = 'current') => {
    if (!reportRef.current) return;
    setIsGenerating(id);

    try {
      // Small delay for UI to update
      await new Promise(resolve => setTimeout(resolve, 500));

      const canvas = await html2canvas(reportRef.current, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff'
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [canvas.width, canvas.height]
      });

      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
      pdf.save(`Nudge_Wealth_Report_${month.replace(' ', '_')}.pdf`);
      
      // If it was a "Generate Now", add to history
      if (id === 'new') {
        const newReport = {
          id: Math.random().toString(36).substring(7),
          date: new Date().toISOString(),
          month: month
        };
        const updatedHistory = [...reportHistory, newReport];
        setReportHistory(updatedHistory);
        localStorage.setItem('nudge_report_history', JSON.stringify(updatedHistory));
      }
    } catch (error) {
      console.error('Error generating PDF:', error);
    } finally {
      setIsGenerating(null);
    }
  };

  return (
    <div className="space-y-8 pb-20">
      {/* Hidden Report Template for PDF Generation */}
      <div className="absolute -left-[9999px] top-0 pointer-events-none">
        <MonthlyReport 
          ref={reportRef} 
          profile={profile} 
          transactions={transactions} 
          formatCurrency={formatCurrency} 
          insights={insights} 
        />
      </div>

      <header className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <h1 className="text-4xl font-bold tracking-tight mb-2 text-nudge-primary-text">Monthly Reports</h1>
          <p className="text-nudge-secondary-text">Comprehensive financial snapshots generated by AI.</p>
        </div>
        <button 
          onClick={() => downloadReport(new Date().toLocaleString('default', { month: 'long', year: 'numeric' }), 'new')}
          disabled={!!isGenerating}
          className="flex items-center gap-2 px-6 py-3 bg-accent-600 hover:bg-accent-500 text-white rounded-2xl font-bold transition-all shadow-lg shadow-accent-600/20 disabled:opacity-50"
        >
          {isGenerating === 'new' ? <Loader2 className="w-5 h-5 animate-spin" /> : <RefreshCw className="w-5 h-5" />}
          Generate Current Report
        </button>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Content: Current Month Summary */}
        <div className="lg:col-span-2 space-y-8">
          <section className="glass rounded-[32px] p-8">
            <div className="flex items-center justify-between mb-8">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-accent-600/10 rounded-2xl flex items-center justify-center">
                  <Eye className="w-6 h-6 text-accent-400" />
                </div>
                <h3 className="text-xl font-bold text-nudge-primary-text">Live Preview</h3>
              </div>
              <span className="px-4 py-1.5 bg-nudge-inverse/10 border border-nudge-border rounded-full text-xs font-bold text-accent-400 uppercase tracking-widest">
                {new Date().toLocaleString('default', { month: 'long' })}
              </span>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="p-6 bg-nudge-inverse/10 border border-nudge-border rounded-2xl">
                <p className="text-nudge-secondary-text text-xs font-bold uppercase tracking-widest mb-2">Monthly Spending</p>
                <p className="text-2xl font-bold text-nudge-primary-text">{formatCurrency(profile.monthly_spending)}</p>
              </div>
              <div className="p-6 bg-nudge-inverse/10 border border-nudge-border rounded-2xl">
                <p className="text-nudge-secondary-text text-xs font-bold uppercase tracking-widest mb-2">Vitality Score</p>
                <div className="flex items-end gap-2">
                  <p className="text-2xl font-bold text-nudge-primary-text">{profile.vitality_score}</p>
                  <span className="text-nudge-secondary-text text-sm mb-1 font-bold">/ 100</span>
                </div>
              </div>
            </div>

            <div className="mt-8 p-6 bg-accent-600/5 border border-accent-500/20 rounded-[24px]">
              <div className="flex items-center gap-2 mb-4">
                <Zap className="w-4 h-4 text-accent-400" />
                <h4 className="text-sm font-bold text-nudge-primary-text uppercase tracking-widest">Top AI Insight</h4>
              </div>
              <p className="text-nudge-primary-text leading-relaxed italic">
                "{insights[0] || "We're still analyzing your spending patterns for this month. Check back soon for deeper insights!"}"
              </p>
            </div>
          </section>

          <section className="glass rounded-[32px] p-8">
             <div className="flex items-center gap-4 mb-8">
              <div className="w-12 h-12 bg-accent-600/10 rounded-2xl flex items-center justify-center">
                <Clock className="w-6 h-6 text-accent-400" />
              </div>
              <h3 className="text-xl font-bold text-nudge-primary-text">Automation</h3>
            </div>
            
            <div className="flex items-center justify-between p-6 bg-nudge-inverse/10 border border-nudge-border rounded-2xl">
              <div>
                <h4 className="font-bold text-nudge-primary-text mb-1">Auto-generate monthly reports</h4>
                <p className="text-sm text-nudge-secondary-text">A fresh report will be ready on the 1st of every month.</p>
              </div>
              <button
                onClick={handleToggleAutoGenerate}
                className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none ${
                  autoGenerate ? "bg-accent-600" : "bg-nudge-inverse/10"
                }`}
              >
                <span
                  className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                    autoGenerate ? "translate-x-6" : "translate-x-1"
                  }`}
                />
              </button>
            </div>
          </section>
        </div>

        {/* Sidebar: History */}
        <section className="glass rounded-[32px] p-8 flex flex-col h-full">
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 bg-accent-600/10 rounded-2xl flex items-center justify-center">
              <FileText className="w-6 h-6 text-accent-400" />
            </div>
            <h3 className="text-xl font-bold text-nudge-primary-text">History</h3>
          </div>

          <div className="space-y-3 flex-1">
            {reportHistory.length > 0 ? (
              reportHistory.map((report) => (
                <div key={report.id} className="group flex items-center justify-between p-4 bg-nudge-inverse/10 border border-nudge-border rounded-2xl hover:bg-nudge-inverse/10 transition-all">
                  <div>
                    <p className="font-bold text-nudge-primary-text">{report.month} Report</p>
                    <p className="text-[10px] text-nudge-secondary-text uppercase font-bold tracking-widest mt-0.5">
                      {new Date(report.date).toLocaleDateString(undefined, { day: 'numeric', month: 'short' })}
                    </p>
                  </div>
                  <button 
                    onClick={() => downloadReport(report.month, report.id)}
                    disabled={isGenerating === report.id}
                    className="p-2.5 bg-accent-600/10 text-accent-400 rounded-xl hover:bg-accent-600 hover:text-white transition-all disabled:opacity-50"
                  >
                    {isGenerating === report.id ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                  </button>
                </div>
              ))
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <FileText className="w-10 h-10 text-nudge-secondary-text mb-4" />
                <p className="text-nudge-secondary-text text-sm font-medium">No archived reports</p>
              </div>
            )}
          </div>
        </section>
      </div>
    </div>
  );
}
